from typing import List, Dict, Any
from mock_simulation.scenarios.base import BaseScenario
from mock_simulation.scenarios.schema import UnifiedEvent
from mock_simulation.scenarios.registry import ScenarioRegistry
from mock_simulation.timelines.engine import TimelineEngine
from mock_simulation.generators.zendesk import ZendeskGenerator

@ScenarioRegistry.register("sla_breach")
class SLABreachScenario(BaseScenario):
    def generate_events(self, timeline: TimelineEngine, org_id: str) -> List[UnifiedEvent]:
        zendesk = ZendeskGenerator(self.faker)

        # 00:00 Customer reports issue
        ticket_event = zendesk.generate_customer_ticket(timeline, org_id, "Cannot login", "I keep getting 500 errors on the login page.")
        ticket_id = ticket_event.metadata["ticket_id"]

        # Time passes beyond SLA limit (e.g. 4 hours for first response)
        timeline.advance_time(hours=5)

        # 05:00 SLA Breach generated by system
        zendesk.generate_sla_breach(timeline, org_id, ticket_id, "first_reply_time")

        return timeline.get_events()

    def expected_findings(self) -> List[Dict[str, Any]]:
        return [
            {"finding_type": "sla_violation", "severity": "high", "description": "First reply time SLA breached"}
        ]

    def expected_graph(self) -> List[Dict[str, Any]]:
        return []

    def expected_slas(self) -> List[Dict[str, Any]]:
        return [{"metric": "first_reply_time", "status": "breached"}]
